branches: 
  - main
repositoryUrl: https://github.com/daileyo/test-semantic-release.git
preset: conventionalcommits
plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - path: '@semantic-release/github'
    failComment: false
    successComment: false