
# REFERENCE
# https://github.com/marketplace/actions/action-for-semantic-release

name: cycjimmy Semantics

on:
  push:
    branches:
      - main
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DRY_RUN: false
  REGISTRY: ghcr.io
  #TODO:  Set owner and name via github context and expansion
  IMAGE_OWNER: daileyo
  IMAGE_NAME: test-semantic-release
  GHCR_TOKEN: ${{ secrets.GH_FULL_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_FULL_TOKEN }

jobs:
  release-please:
    name: Check & Version
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.cycjimmy_release.outputs.new_release_published }}
      previousVersion: ${{ steps.cycjimmy_release.outputs.last_release_version }}
      newVersion: ${{ steps.cycjimmy_release.outputs.new_release_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: unique requirements
        run: |
          npm install --save-dev conventional-changelog-conventionalcommits
          
      - name: Analyze Commits for Semantic Release
        id: cycjimmy_release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ env.SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ env.GHCR_TOKEN }}
          
      - name: another test
        env:
          a: ${{ steps.cycjimmy_release.outputs.new_release_published }}
          b: ${{ steps.cycjimmy_release.outputs.last_release_version }}
          c: ${{ steps.cycjimmy_release.outputs.new_release_version }}
        run: |
          echo "++++++++++++++++++++++++++"
          echo "changed:  $a"
          echo "previous: $b"
          echo "next:     $c"
          echo "++++++++++++++++++++++++++"
  
  publish:
    needs: release-please
    name: Publish Image
    runs-on: ubuntu-latest
    if: needs.release-please.outputs.changed == 'true'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: check version info
        env:
          changed:          ${{ needs.release-please.outputs.changed }}
          newVersion:       ${{ needs.release-please.outputs.newVersion }}
          previousVersion:  ${{ needs.release-please.outputs.previousVersion }}
          imageName:        ${{ ${github.repository#/*} }}
          owner:            ${{ ${github.repository%*/} }}
        run: |
          echo "*********************************************"
          echo "changed:    $changed"
          echo "previous:   $previousVersion"
          echo "newVersion: $newVersion"
          echo "owner:      $owner"
          echo "imageName:  $imageName"
          echo "*********************************************"

      - name: Log Into Registry
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ env.GHCR_TOKEN }}


      - name: Build and Publish Image
        uses: docker/build-push-action@v3
        with:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ needs.release-please.outputs.newVersion }}
          