
name: Semantics

on:
  push:
    branches:
      - main
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DRY_RUN: false
  REGISTRY: ghcr.io
  IMAGE_OWNER: daileyo
  IMAGE_NAME: test-semantic-release
  GHCR_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Would be nice for workflow, but there appears to be an issue with using this action within a fork
      # https://github.com/actions/toolkit/issues/465
      # TODO:  Investigate further

      - name: Analyze Commits for Semantic Release
        id: two
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ env.SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ env.GHCR_TOKEN }}
        with:
          dry_run: ${{ env.DRY_RUN }}

      - name: Log Into Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ env.GHCR_TOKEN }}

      - name: Sanity Test
        env:
          TAG: ${{ github.ref_name }}
          TYPE: ${{ github.ref_type }}
        run: |
          echo "**********"
          echo TYPE:  $TYPE
          echo TAGE:  $TAG
          echo "**********"

      - name: Build and Publish Image
        uses: docker/build-push-action@v3
        env: 
          #This is dependent on a tag existing on the latest commit in the branch. It will not work otherwise.
          #https://github.com/orgs/community/discussions/26686#discussioncomment-3396593
          TAG: ${{ github.ref_name }}
        with:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          