
name: Semantics

on:
  push:
    branches:
      - main
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DRY_RUN: false
  REGISTRY: ghcr.io
  #TODO:  Set owner and name via github context and expansion
  IMAGE_OWNER: daileyo
  IMAGE_NAME: test-semantic-release
  GHCR_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}

jobs:
  version:
    name: Check & Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Analyze Commits for Semantic Release
        id: sem_rel
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ env.SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ env.GHCR_TOKEN }}
        with:
          dry_run: ${{ env.DRY_RUN }}


      - name: Check for Release
        if: ${{ steps.sem_rel.outputs.release-version }} == null
        run: echo "!!!!!!!!!! No relese generated.  Image publish will be skipped. !!!!!!!!!!"

 
      - name: Check result
        #if: ${{ env.DRY_RUN == 'false' }}
        #if: ${{ version.steps.sem_rel.outputs.release-version }} != null
        env:
          TAG:  ${{ steps.sem_rel.outputs.release-version }}
          REFERENCE: ${{ github.ref_name }}
        run: |
          echo "****************************************"
          echo "TAG:        $TAG"
          echo "REFERENCE:  $REFERENCE"
          echo "Full Ref:   $GITHUB_REF"
          echo "****************************************"
  
  publish:
    
    name: Publish Image
    runs-on: ubuntu-latest
    needs: version
    # if: ${{ env.DRY_RUN == 'false' }}
    steps:

      - name: Check result
        #if: ${{ env.DRY_RUN == 'false' }}
        #if: ${{ version.steps.sem_rel.outputs.release-version }} != null
        env:
          TAG:  ${{ steps.sem_rel.outputs.release-version }}
          REFERENCE: ${{ github.ref_name }}
        run: |
          echo "****************************************"
          echo "TAG:        $TAG"
          echo "REFERENCE:  $REFERENCE"
          echo "Full Ref:   $GITHUB_REF"
          echo "****************************************"

      - name: Log Into Registry
        if: ${{ env.DRY_RUN == 'false' }}
       # if: ${{ env.DRY_RUN == 'false' && .sem_rel.outputs.release-version != null }}  
        uses: docker/login-action@v2
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }} 
          password: ${{ env.GHCR_TOKEN }}


      - name: Build and Publish Image
        if: ${{ env.DRY_RUN == 'false' }}
        uses: docker/build-push-action@v3
        env: 
          #This is dependent on a tag existing on the latest commit in the branch. It will not work otherwise.
          #https://github.com/orgs/community/discussions/26686#discussioncomment-3396593
          TAG: ${{ github.ref_name }}
        with:
           context: .
           push: true
           tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest, ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          