
name: Semantics

on:
  push:
    branches:
      - main
  #Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  DRYRUN: true

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Analyze Commits
        uses: actions/checkout@v3
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}
          GH_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
        with:
          dry_run: DRYRUN
      - name: Get Tag
        id: vars
        run: echo "::set-output name=tag::${git describe --tags abbrev=0}"; echo "${{ steps.vars.output.tag }}"; echo "   ++++   "
      - name: Build and Publish Image
        env:
          BLAH: ${{ steps.vars.output.tag }}
        run: echo "***** ${{ steps.vars.output.tag }} "
