
#  REFERENCES
#  https://github.com/liatrio/product-operator/blob/main/.github/workflows/post-release.yaml
#  https://github.com/liatrio/lead-terraform/blob/master/.github/workflows/release.yml

name: Semantic Release

on:
  push:
    branches:
      - main
    paths:
      - 'modules/**'
      - 'stacks/**'
      - 'stages/**'
      - '.releaserc.yaml'
      - '.github/workflows/release.yml'  
  workflow_dispatch:
env:
  GHCR_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_SEMANTIC_RELEASE_TOKEN }}

concurrency:
  group: release

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.release.outputs.changed }}
      previousVersion: ${{ steps.release.outputs.changed }}
      newVersion: ${{ steps.release.outputs.changed }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Yarn for Local Testing
        run: |
          npm install --location=global yarn

      - name: Release Pakage
        id: rel_package
        uses: liatrio/github-actions/conventional-release@master
        env:
          GITHUB_TOKEN: $ {{ env.SEMANTIC_RELEASE_TOKEN }}