
name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GHCR_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_FULL_TOKEN }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Install Yarn
      run: npm install -g yarn
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: wrapper check
      uses: liatrio/github-actions/conventional-release@master
      env:
        GITHUB_TOKEN: ${{ env.SEMANTIC_RELEASE_TOKEN }}