
#  REFERENCES
#  https://github.com/liatrio/product-operator/blob/main/.github/workflows/post-release.yaml
#  https://github.com/liatrio/lead-terraform/blob/master/.github/workflows/release.yml

name: Semantic Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
env:
  GHCR_TOKEN: ${{ secrets.GHCR_DAILEYO_TOKEN }}
  SEMANTIC_RELEASE_TOKEN: ${{ secrets.GH_FULL_TOKEN }}
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: Install Yarn
      run: npm install -g yarn
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: wrapper check
      #id: sem_ver
      uses: liatrio/github-actions/conventional-release@master
      env:
        GITHUB_TOKEN: ${{ env.SEMANTIC_RELEASE_TOKEN }}
    
    - name: check version
      env:
        NEW: ${{ steps.validate.outputs.releaseVersion }}
      run: | 
        echo "RELEASE VERSION: $RELEASE_VERSION"
        echo "TAG : $NEW"